#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleFingerprint.Resource", IsApplication=true)]

namespace SampleFingerprint
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int black = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int btn_disabled_end = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int btn_disabled_start = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int btn_enabled_end = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int btn_enabled_start = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int btn_pressed_end = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int btn_pressed_start = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int colorAccent = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int colorPrimary = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int colorPrimaryDark = 2130771977;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int activity_horizontal_margin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int activity_vertical_margin = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int border_width = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int corner_radius = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int fingerprint_height = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int fingerprint_width = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int padding = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int tab_bar_height = 2130837511;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int fingerprint0 = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int image_border_off = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int image_border_on = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int page_btn_bkgd = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int page_btn_fgd = 2130903044;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int capture_button = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int fingeprint_info_textview = 2130968577;
			
			// aapt resource value: 0x7F040004
			public const int fingerprint_one_label = 2130968580;
			
			// aapt resource value: 0x7F040002
			public const int finger_one_imageview = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int finger_two_imageview = 2130968579;
			
			// aapt resource value: 0x7F040005
			public const int match_button = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int open_close_button = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int status_textview = 2130968583;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int Main = 2131034112;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int Icon = 2131099648;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int bio_init_failed = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int bio_init_good = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int capture = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int close = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int fingerprint_one_imageview_label = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int fingerprint_selection_label = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int fingerprint_two_imageview_label = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int hello = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int match = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int open = 2131165194;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int PageButton = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int Spinner = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int StatusInfo = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int TextInfo = 2131230723;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
