#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleFingerprint.Resource", IsApplication=true)]

namespace SampleFingerprint
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int black = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int btn_disabled_end = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int btn_disabled_start = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int btn_enabled_end = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int btn_enabled_start = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int btn_pressed_end = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int btn_pressed_start = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int colorAccent = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimary = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int colorPrimaryDark = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int activity_horizontal_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int activity_vertical_margin = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int border_width = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int corner_radius = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int fingerprint_height = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int fingerprint_width = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int padding = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int tab_bar_height = 2131099653;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fingerprint0 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int image_border_off = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int image_border_on = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int page_btn_bkgd = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int page_btn_fgd = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public const int capture_button = 2131296260;
			
			// aapt resource value: 0x7f090007
			public const int fingeprint_info_textview = 2131296263;
			
			// aapt resource value: 0x7f090000
			public const int finger_one_imageview = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int finger_two_imageview = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int fingerprint_one_label = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int match_button = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int open_close_button = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int status_textview = 2131296262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int bio_init_failed = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int bio_init_good = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int capture = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int close = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int fingerprint_one_imageview_label = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int fingerprint_selection_label = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int fingerprint_two_imageview_label = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int match = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int open = 2131165188;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int PageButton = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Spinner = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int StatusInfo = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int TextInfo = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
